config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root  'webpages#index'
  resources :webpages
  resources :favs
  get '/webpages/:id/:category' => 'webpages#show'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    # user ||= User.first # guest user (not logged in)
    # if user && user.admin?
    # can :access, :rails_admin       # only allow admin users to access Rails Admin
    # can :dashboard           
    #   can :manage, :all
    # else
    #   can :read, :all                   # allow everyone to read everything
    # end

    # Define abilities for the passed in user here. For example:
    #
    # user ||= User.new # guest user (not logged in)
      if user && user.admin?
        can :access, :rails_admin       # only allow admin users to access Rails Admin
        can :dashboard           
        can :manage, :all
        # can :read, :all 
      else
        can :read, :all 
        # can :access, :all
         # :rails_admin       # only allow admin users to access Rails Admin
        # can :dashboard           
        # can :manage, :all
      end
    
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
   has_many :webpages
end

app/models/fav.rb
class Fav < ActiveRecord::Base
  belongs_to :user
  belongs_to :webpage
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role
  has_many :webpages

  # Favorite recipes of user
  has_many :favs # just the 'relationships'
  has_many :favorites, through: :favs, source: :webpage # the actual recipes a user favorites  before_create :set_default_role
  
  def admin?
    # user = self

    # puts self.inspect
    # user = User.first
    # puts user.role_id.inspect
    role_id == 3 # If you have id == 0 for admin
  end

  private
  def set_default_role
    self.role ||= Role.find_by_name('registered')
  end

end

app/models/webpage.rb
class Webpage < ActiveRecord::Base
	belongs_to :category
	belongs_to :user

	# Favorited by users
	has_many :favs # just the 'relationships'
	has_many :favorited_by, through: :favs, source: :user 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_filter :authenticate_user! #doesn't allow viewing app content without login  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # include CanCan::ControllerAdditions
  # rescue_from CanCan::AccessDenied do |exception|
  #   redirect_to root_path, :alert => exception.message
  # end
  helper_method :current_ability, :send_simple_message, :get_user_favs
  def current_ability
   @current_ability ||= Ability.new(current_user)
  end

  def get_user_favs
   @user = current_user
   @user_favs = Fav.where(:user_id => @user.id)
  end

  def send_simple_message
   RestClient.post "https://api:key-4c77520a1f204f3f770dc88b91b26177"\
   "@api.mailgun.net/v3/sandbox2c8be1a58fdf465aa9bde6da35cde98c.mailgun.org/messages",
   :from => "Mailgun Sandbox <postmaster@sandbox2c8be1a58fdf465aa9bde6da35cde98c.mailgun.org>",
   :to => "Krum Manoilov <kk.manoilov@gmail.com>",
   :subject => "Hello Krum Manoilov",
   :text => "Congratulations Krum Manoilov, you just sent an email with Mailgun!  You are truly awesome!  You can see a record of this email in your logs: https://mailgun.com/cp/log .  You can send up to 300 emails/day from this sandbox server.  Next, you should add your own domain so you can send 10,000 emails/month for free."
  end
  # private
  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
 #  def show
	# category_id = params[:category_id]
 #    @category = Category.find(category_id)
 #    @webpages = @category.webpages.order("webpages.created_at DESC")
 #  end
 def index
 end
end

app/controllers/favs_controller.rb
class FavsController < ApplicationController
  before_action :authenticate_user!
  helper_method :current_ability
  skip_before_filter :verify_authenticity_token

  def new
  	
  	@user = current_user	
    # Rails.logger.debug("My wiwi: #{@user.inspect}")

  	if @user && params[:page]
       @user.favs.create(:webpage_id => params[:page], :user_id => @user)
       redirect_to webpages_path
  	else
  	   redirect_to sign_up_path
  	end
    

  	
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!  # Tell devise to use :user map
end

app/controllers/webpages_controller.rb
class WebpagesController < ApplicationController
   # before_action :authenticate_user!  # Tell devise to use :user map
   helper_method :current_ability, :get_user_favs

   def index
   	if params[:category]
     @webpages  = Webpage.where(:category => params[:category])
     @page  = Webpage.where(:category => params[:category]).first
     @cat = params[:category]
    else
     @webpages  = Webpage.includes([:category]).order('categories.name ASC').all
    end    
   	 @categories = Category.all
    if user_signed_in?
     @user_favs  = get_user_favs
    end
   end

   def show
    if params[:category]
     @webpages  = Webpage.where(:category => params[:category])
     @cat = params[:category]
    else
     @webpages  = Webpage.includes([:category]).order('categories.name ASC').all
    end
  	# @webpages   = Webpage.includes([:category]).order('categories.name ASC').all
   	@categories = Category.all
  	@page    = Webpage.find(params[:id])
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/webpages_helper.rb
module WebpagesHelper
  # def allow_user_favourite?(webpage)
  #   return false unless current_user
  #   @webpage.id == current_user.id
  # end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top no-margin-navbar">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          
            <li>
              <%= link_to('Излес', destroy_user_session_path, :method => :delete) %>
            </li>
          <% else %>
            <li>
              <%= link_to('Влез', new_user_session_path)  %>  
            </li>
          <% end %>
            <li><a href="/users/sign_up">Регистрирай се</a></li>
          <% if user_signed_in? %>
            <li><a href="#">Профил</a></li>
          <% end %>
            <li><a href="#">Помощ</a></li>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/_modalform.html.erb
<!-- Button trigger modal -->
<!-- <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button> -->

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Любими Кавички</h4>
      </div>
      <div class="modal-body">
        <h3>За да можете да добавите вашите любими страници, се Регистрирайте 
<%= link_to('тук', new_user_session_path) %>!
        </h3>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Затвори</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kavichka</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <script type="text/javascript">
        function iframe_resize(){
            var body = document.body,
            html = document.documentElement,
            height = Math.max(body.scrollHeight, body.offsetHeight, 
          html.clientHeight, html.scrollHeight, html.offsetHeight);
            if (parent.postMessage) {
                parent.postMessage(height, "http://localhost:3000");
            }
        }
        </script>
         <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">

    google.load("feeds", "1");

    function initialize() {
      
      var feed = new google.feeds.Feed("http://www.blitz.bg/rss.php?news");
      feed.setResultFormat(google.feeds.Feed.JSON_FORMAT);
      // console.log(JSON.parse(feed));
      feed.load(function(result) {
        if (!result.error) {
          // var wrapper = document.getElementById("kavichka-wrap");
          var container = document.getElementById("feed");
          for (var i = 0; i < result.feed.entries.length; i++) {
      
            var entry = result.feed.entries[i];
            var div = document.createElement("div");
            var div2 = document.createElement("div");
            var div3 = document.createElement("div");
            // $('#feed>div>img').addClass("kavichka-thumb");
            // div2.className = "";
            // div3.className = "aClassName";

            // div2.innerHTML =  entry.content;

            var images = [];
            
            $(entry.content).each(function(){
              images = entry.content;
             images =  $(images).get();
            });
           
            $(container).append(div);
            $(div).addClass('col-md-3');
            $('#feed>div>img').addClass('img-responsive');
            $(div).append(images);
            div.appendChild(document.createTextNode(entry.title));

          }
        }
      });
    }
    google.setOnLoadCallback(initialize);

// html
// div
//   img
//   link(title)
//   content
//   date
// div

    </script>
</head>
<body onload="iframe_resize();">
<%= render 'layouts/header'%>
<%= render 'layouts/modalform'%>
<div class="container-fluid">
   <div class="row">
    		<%= yield %>
   </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/webpages/index.html.erb
<div class="col-sm-3 col-md-2 sidebar kavichka-sidebar">
  <a class="logo-topbar" href="<%= root_url %>"><img src="/LogoDark.svg"/></a>
  <ul class="nav nav-main">
   <li><a href="">КАВИЧКИ</a></li>
   <li><a href="">ЛЮБИМИ</a></li>
   <li>
      <div class="btn-group">
        <a class=" dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          КАТЕГОРИИ <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><%= link_to "All", root_path %></li>
              <% @categories.each do |category| %>
            <li><%= link_to category.name, webpages_path(:category=>category.id) %></li>
          <% end %>
        </ul>
      </div>
    </li>
  <li class="websites-sidebar">САЙТОВЕ</li>

  </ul>
  <ul class="nav nav-pages">
   <% @webpages.each do |webpage| %>

      <li>
       <div class="row sidebar-webpage-wrapper">
         
         <div class="col-md-8">
           <% if @cat.present? %>
              <%= link_to webpage.name, webpage_path(webpage.id,:category=>@cat) %>
           <% else %>
              <%= link_to webpage.name, webpage_path(webpage) %>
           <% end %>
         </div>

         <div class="col-md-4 icon-holder">
           <% if user_signed_in? %>
             <% if Fav.where(:webpage_id => webpage.id).blank? %>
              <%= link_to "", new_fav_path(:page => webpage.id) ,  class: "un-liked glyphicon glyphicon-heart" %>
             <% else %>
              <i class="glyphicon glyphicon-heart" style="color: blue;"></i>
             <% end %>
           <% else %>
           <button type="button" class="override-modal btn" data-toggle="modal" data-target="#myModal">
              <i id="not-user-popup" class="glyphicon glyphicon-heart un-liked"></i>
          </button>
<!-- Modal -->
           <%end%>
         </div>

       </div>
      </li>
  <% end %>
  </ul>

</div>
<div class="col-sm-9 col-sm-offset-3 col-md-9 col-md-offset-3 main">
   
   <div id="kavichka-wrap" class="col-md-12">
     <div id="feed" style="background-color: #fff;">
     </div>
   </div>

  <div class="row placeholders">
    <div class="embed-responsive embed-responsive-16by9">
    <% if @page.present? %>
       <iframe id="content-iframe" class="iframe-obj embed-responsive-item" src="<%= 
       @page.link %>"></iframe>   
    <% else %>
       <iframe class="iframe-obj embed-responsive-item" src="<%=%>">
       </iframe> 
    <% end %>
    </div>
  </div>

</div>

app/views/webpages/show.html.erb
<div class="col-sm-3 col-md-2 sidebar kavichka-sidebar">
  <a class="logo-topbar" href="<%= root_url %>"><img src="/LogoDark.svg"/></a>
  <ul class="nav nav-main">
   <li><a href="">КАВИЧКИ</a></li>
   <li><a href="">ЛЮБИМИ</a></li>
   <li>
      <div class="btn-group">
        <a class=" dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          КАТЕГОРИИ <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><%= link_to "All", root_path %></li>
              <% @categories.each do |category| %>
            <li><%= link_to category.name, webpages_path(:category=>category.id) %></li>
          <% end %>
        </ul>
      </div>
    </li>
  <li class="websites-sidebar">САЙТОВЕ</li>

  </ul>
  <ul class="nav nav-pages">
   <% @webpages.each do |webpage| %>

      <li>
       <div class="row sidebar-webpage-wrapper">
         
         <div class="col-md-8">
           <% if @cat.present? %>
              <%= link_to webpage.name, webpage_path(webpage.id,:category=>@cat) %>
           <% else %>
              <%= link_to webpage.name, webpage_path(webpage) %>
           <% end %>
         </div>

         <div class="col-md-4 icon-holder">
           <% if user_signed_in? %>
             <% if Fav.where(:webpage_id => webpage.id).blank? %>
              <%= link_to "", new_fav_path(:page => webpage.id) ,  class: "un-liked glyphicon glyphicon-heart" %>
             <% else %>
              <i class="glyphicon glyphicon-heart" style="color: blue;"></i>
             <% end %>
           <% else %>
           <button type="button" class="override-modal btn" data-toggle="modal" data-target="#myModal">
          <i id="not-user-popup" class="glyphicon glyphicon-heart un-liked"></i>

</button>

<!-- Modal -->

           <%end%>
         </div>

       </div>
      </li>
  <% end %>
  </ul>

</div>
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

  <div class="row placeholders">
    <div class="embed-responsive embed-responsive-16by9">
      <iframe id="zino_iframe" class="iframe-obj embed-responsive-item" src="<%= @page.link %>">
          
      <iframe>  
         <script type="text/javascript">
        var zino_resize = function (event) {
            if (event.origin !== "http://dir.bg") {
                return;
            }
            var zino_iframe = document.getElementById('zino_iframe');
            if (zino_iframe) {
                zino_iframe.style.height = event.data + "px";
            }
        };
        if (window.addEventListener) {
            window.addEventListener("message", zino_resize, false);
        } else if (window.attachEvent) {
            window.attachEvent("onmessage", zino_resize);
        }
        </script> 
    </div>
  </div>

</div>